#!/bin/bash
usage (){
echo "You need to call this script like this :"
echo "$0 my-preso.md"
}

if [ -z "$1" ] ; then
  usage
  exit 1
fi

md_file="$1"
echo rendering RemarkJS html output file to output/${md_file/.md}.html
cat remarkjs/remarkjs-header.html > output/${md_file/.md}.html
cat $md_file >> output/${md_file/.md}.html
cat remarkjs/remarkjs-footer.html >> output/${md_file/.md}.html
